Creación de README.md
xCyal/A-Tracker pull request #1
Opened 2021-11-20 15:24 UTC by xCyal

Se ha creado el README.md con una breve descripción del problema.

2021-11-21 12:05 UTC, JJ approved these changes
:+1:  por empezar, pero realmente deberías mirar con más detenimiento el guión del hito para el tipo de problema que se requiere en esta asignatura y cómo describirlo correctamente.

2021-11-21 12:05 UTC, JJ commented on README.md
> +Antiguamente este tipo de analisis era muy complicado de realizar, especialmente a nivel personal donde no todas las personas tenían los recursos para analizar sus estadísticas o era un proceso muy t
typo

2021-11-21 12:05 UTC, JJ commented on README.md
> +A-Tracker se creará con la intención de proporcionar al usuario una herramienta donde pueda introducir los datos de sus partidas creando un historial de las mismas, con datos detallados de las decisi
Esto no es un problema, es una tarea. Un problema tiene que significar un claro beneficio para el usuario, y no pedirle que haga cosas sin que el beneficio esté claro. En este caso específico, no debería pedirse al usuario ninguna información, sino buscar la manera de obtenerla.

2021-11-21 12:05 UTC, JJ commented on README.md
> +Para tener un mejor servicio, se creara un sistema de usuarios donde cada perfil tenga un registro historico de partidas, sobre el cual se obtendran estadísticas de las mismas y se analizaran de mane
No queda clara la lógica de negocio. "Estadísticas" puede ser contar cosas. Tiene que haber una lógica de negocio clara. Por favor, revisa el guión de este objetivo y pasa la lista de comprobación.

2021-11-21 12:06 UTC, JJ requested changes
OK, le he dado demasiado pronto al botón. No está aprobado, tendrás que seguir intentándolo.

2021-11-21 12:10 UTC, xCyal commented
> OK, le he dado demasiado pronto al botón. No está aprobado, tendrás que seguir intentándolo.

Perfecto, es cierto que tenía mis dudas sobre si la idea era buena para el proyecto, pero tenía ganas de realizar esta tarea desde hace un tiempo, voy a intentar enfocarla mejor o en caso de no saber como, cambiar completamente de proyecto.

2021-11-21 12:12 UTC, JJ commented
> > OK, le he dado demasiado pronto al botón. No está aprobado, tendrás que seguir intentándolo.
> 
> Perfecto, es cierto que tenía mis dudas sobre si la idea era buena para el proyecto, pero tenía ganas de realizar esta tarea desde hace un tiempo, voy a intentar enfocarla mejor o en caso de no saber como, cambiar completamente de proyecto.

Cualquier idea es buena, pero realmente tienes que expresarla de forma que quede claro que hay una lógica de negocio y que digas claramente qué problema es el que quieres solucionar. No pongas primero la solución, y después el problema.

2021-11-22 11:20 UTC, xCyal commented
> Cualquier idea es buena, pero realmente tienes que expresarla de forma que quede claro que hay una lógica de negocio y que digas claramente qué problema es el que quieres solucionar. No pongas primero la solución, y después el problema.

Disculpe por el PR, pensaba que había que actualizar la versión en cada update del respositorio. He intentando plantear de nuevo el problema sin cambiar la idea principal, de manera que se ajuste más a lo especificado, de nuevo en caso de no encontrar la manera, cambiaré a algo ortodoxo.

2021-11-22 11:26 UTC, JJ commented
Por favor, recuerda decir explícitamente "Listo para revisión" para que yo lo revise. Entiendo que ahora está listo, paso a revisarlo.

2021-11-22 11:28 UTC, JJ approved these changes
OK, hablas de "generar" y también de "mejorar", así que está claro que hay un beneficio para el usuario. También "generar" es una lógica de negocio implícita, igual que "comparar". 
Por favor, recuerda que tienes que codificar tú la lógica de negocio... Y lee atentamente el objetivo 1, por favor.

2021-11-22 11:40 UTC, merged