IV Objetivo 3 [IV-21-22]
xCyal/A-Tracker pull request #13
Opened 2022-01-01 21:11 UTC by xCyal

* [x]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x]  ¿Ese issue está asignado a un milestone?
* [x]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x]  ¿El PR, que también es un issue, está asignado al mismo milestone?

2022-01-01 21:15 UTC, JJ commented
⛹ Revisores → @gomares @danifm1321 @vlljuan99

2022-01-04 11:52 UTC, danifm1321 requested changes
En general, considero que falta documentación. Se trata de la manera en la que debes enfocarla: no tienes que documentar por qué has elegido x herramienta, sino el proceso de investigación y comparación que te ha llevado hacia la herramienta x. A ver que comentan también mis compañeros @gomares y @vlljuan99

2022-01-04 11:52 UTC, danifm1321 commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a pip tras algo de investigación debido a que su eficiencia respecto a este último es mayor, dando una mejor performance. Además, es mucho más sencillo en su instalación y
¿Has considerado otras alternativas además de poetry y pip? Yo le echaría un ojo a otros gestores de dependencias que hay disponibles.

Igualmente, ¿eficiencia en qué sentido? Si has medido los tiempos y has obtenido datos, deberías incluirlos. Si no, ¿qué característica es la que hace que poetry sea más eficiente?

2022-01-04 11:52 UTC, danifm1321 commented on docs/criteriosObjetivo3.md
> +Se trata de un task runner especificamente utilizado para python, que en muchos sentidos tiene una forma de uso similar a Make con el cual la mayoría de desarrolladores estan familiarizados. Además,
¿Qué otros task runner has considerado? ¿Qué características te han hecho decantarte por invoke en vez de por make, el cual has mencionado? A mi parecer, make tiene también una documentación bastante adecuada.

2022-01-04 11:52 UTC, danifm1321 commented on iv.yaml
> +test: test/test_tracker.py
Test no es necesario para este objetivo. Te va a servir para el siguiente, así que déjalo que tampoco molesta, solo comento.

2022-01-04 11:52 UTC, danifm1321 commented on tasks.py
> +   run("pylint -E tracker")
También deberías dar una pequeña justificación de por que usas la orden pylint para comprobar la sintaxis.

2022-01-05 09:38 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a pip tras algo de investigación debido a que su eficiencia respecto a este último es mayor, dando una mejor performance. Además, es mucho más sencillo en su instalación y
> En general, considero que falta documentación. Se trata de la manera en la que debes enfocarla: no tienes que documentar por qué has elegido x herramienta, sino el proceso de investigación y comparación que te ha llevado hacia la herramienta x. A ver que comentan también mis compañeros @gomares y @vlljuan99

Estoy de acuerdo con algunos puntos de tu comentario, respecto al gestor de dependencias, voy a intentar explicar algo mejor la elección y añadir alguno más que he podido encontrar durante el proceso de elección.

Sobre el task runner en cambio, se trata de una elección algo más personal. Principalmente debido a que durante toda la carrera hemos utilizado make, y el uso de invoke en este caso es personalmente debido a su gran parecido con este, además de tener ciertas ventajas mencionadas como la documentación o ser especifico para python, permitiendome salir de la zona de confort que sería haber elegido make directamente respecto a otros task runners sin sentir estar utilizando algo completamente diferente, porque como ya digo, la sintaxis se hace bastante amena.

También es cierto que no explico nada de pylint, voy a añadir una breve descripción de lo que es un linter y el motivo de elegir este. 

Muchas gracias por tu feedback y haber invertido tiempo en revisar mi objetivo, se agradece de verdad!

2022-01-05 15:35 UTC, gomares commented
Mucho ánimo!

2022-01-05 16:43 UTC, xCyal commented
> El objetivo es funcional lo suficiente como para dar mi visto bueno pero a la documentación sí que le añadiría un poquito más para que lo apruebes al 100%.

He añadido algunas cosas sobre pylint y nombrado algunos otros gestores que he tenido en cuenta, muchas gracias por el feedback!

2022-01-05 16:43 UTC, xCyal commented
> Mucho ánimo!

Gracias! Lo mismo digo!

2022-01-05 16:44 UTC, xCyal commented
Listo para revisión, estoy ahora mismo trabajando en el branch de Objetivo-4 dando por hecho que las funcionalidades de este están completas.

2022-01-06 12:23 UTC, JJ commented on tasks.py
> +   run("pylint -E tracker")
Pista: pylint no es necesaria para comprobar la sintaxis. En general, hazle caso a @danifm1321.

2022-01-06 13:10 UTC, danifm1321 requested changes
Deberías darle otro repaso a lo que te he puesto. La justificación que me has puesto en el comentario de github deberías añadirla en la documentación, ya que al final es un criterio que has usado para la elección de invoke.

2022-01-06 17:39 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +La documentación de Poetry es bastante clara y amigable para usuarios poco experimentados en su uso. Poetry nos permite su completo manejor desde un único archivo llamado pyproject.toml, cuya sintaxi
Creo que tienes razón en este aspecto, se trata tan solo de datos leídos durante el proceso de selección del gestor, creo que dado que no puedo comprobar dicho dato, voy a optar por no mencionarlo, ya que lo que si es cierto es que los otros criterios seguidos si los he comprobado en mi propio trabajo.

2022-01-06 18:00 UTC, xCyal commented on tasks.py
> +   run("pylint -E tracker")
He añadido la justificación de usar pylint (y como podría comprobar si compila un archivo sin tener en cuenta posibles errores de estilo a la hora de escribir el código).

2022-01-06 18:22 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +En general poetry ha resultado a mi parecer una mejor opción, basandome no solo en los datos encontrados si no tambien en opiniones y críticas de usuarios que actualmente estan desarrollando proyecto
Listo, creo que ahora no solo he indicado las ventajas de poetry. He añadido brevemente mi idea a la hora de utilizar los otros mencionados.

2022-01-06 18:28 UTC, xCyal commented
En general, creo haber mejorado la documentación: 

- He añadido a la elección del gestor de dependencias los motivos de usar poetry respecto a los otros mencionados. 
- He mencionado mis motivos personales para usar Invoke frente a make en la documentación, que, al final, es un motivo de peso en mi elección del mismo.
- A la documentación de pylint se ha añadido una breve descripción de lo que supuestamente debe hacer la función check() para el objetivo-3, y porque usar pylint te ayuda, además de a lo necesario para este objetivo (compilar), a mantener el código a nivel de estilo (y otras muchas funcionalidades que añade, las cuales obviamente no han sido revisadas dada la escala del proyecto).

Creo que esta vez si está listo para revisión. En poco tiempo tendré el objetivo-4 listo y espero tener una mejor documentación para este desde el principio teniendo en cuenta lo aprendido en este. 

Muchas gracias de nuevo a @danifm1321 , @gomares y @JJ por vuestro tiempo.

2022-01-07 11:41 UTC, gomares approved these changes

2022-01-08 19:14 UTC, JJ commented on pyproject.toml
> +pylint = "^2.4.4"
`pylint` no hace falta, no ha hecho falta nunca, y hemos repetido muchas veces en clase que no hace falta.

2022-01-08 19:18 UTC, JJ requested changes
Lo siento, no pasa.

2022-01-08 19:18 UTC, JJ commented on README.md
> +Para instalar poetry:
Si vas a copiar lo que viene en el manual de poetry, no pongas nada (o pon un enlace)

2022-01-08 19:18 UTC, JJ commented on README.md
> +**poetry run inv check**
Si necesitas hacer esto, es que `invoke` está mal instalado y en realidad estás usando `poetry` como task runner.

2022-01-08 19:18 UTC, JJ commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a otros como pip o pipenv.
No se dice qué se ha elegido, se establecen criterios para la elección. Además, nadie ha pedido que se elija gestor de dependencias.

2022-01-08 19:18 UTC, JJ commented on docs/criteriosObjetivo3.md
> +En general poetry ha resultado a mi parecer una mejor opción, basandome no solo en los datos encontrados si no tambien en opiniones y críticas de usuarios que actualmente estan desarrollando proyecto
@danifm1321 `npm` es para javascript, no para Python.

2022-01-08 19:18 UTC, JJ commented on docs/criteriosObjetivo3.md
> +Se trata de un task runner especificamente utilizado para python, que en muchos sentidos tiene una forma de uso similar a Make con el cual la mayoría de desarrolladores estan familiarizados. Además,
No estás poniendo los criterios de uso, estás diciendo que has elegido `invoke`. Cuando un revisor como @danifm1321 te dice algo, no es para que le expliques, es para que hagas cambios.

2022-01-08 20:08 UTC, xCyal commented on README.md
> +**poetry run inv check**
Cierto, no esta mal instalado, ha sido un error correrlo desde Poetry.

2022-01-08 20:17 UTC, xCyal commented on pyproject.toml
> +pylint = "^2.4.4"
> Pylint lo pondría en dev-dependencies.

Completamente de acuerdo, los he movido a dev.


> `pylint` no hace falta, no ha hecho falta nunca, y hemos repetido muchas veces en clase que no hace falta.

Soy consciente, he intentado especificar el porque querría usarlo en el proyecto y como se podría realizar sin su uso en la documentación.

2022-01-08 20:22 UTC, xCyal commented on README.md
> +Para instalar poetry:
Perfecto, voy a optar por colocar un enlace.

2022-01-08 20:23 UTC, xCyal commented on README.md
> +**poetry run inv check**
Corregido, error grave ya que yo mismo al utilizar inv no estaba utilizando Poetry.

2022-01-08 20:23 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a otros como pip o pipenv.
Voy a especificar que **he elegido poetry**, es cierto que no se menciona realmente.

2022-01-08 21:19 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +Se trata de un task runner especificamente utilizado para python, que en muchos sentidos tiene una forma de uso similar a Make con el cual la mayoría de desarrolladores estan familiarizados. Además,
Tal y como el me indicaba en su comentario, he añadido un párrafo adicional en el que explico los motivos personales para la elección de invoke.

2022-01-08 21:24 UTC, xCyal commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a otros como pip o pipenv.
> No se dice qué se ha elegido, se establecen criterios para la elección. Además, nadie ha pedido que se elija gestor de dependencias.

He modificado la documentación para especificar que se ha usado Poetry como gestor de dependencias. Respecto a la segunda parte, he tenido en cuenta los comentarios de mis compañeros y he intentado reflejar en la documentación las decisiones tomadas en el proyecto.

2022-02-08 12:57 UTC, closed without merging