IV Objetivo 4 [IV-21-22] Closes #14
xCyal/A-Tracker pull request #15
Opened 2022-01-06 22:29 UTC by xCyal

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando? Relacionada con M0 y el sistema de analisis de partidas (puntuación)
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito? 
* [x]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2022-01-06 22:48 UTC, JJ commented
⛹ Revisores → @danifm1321 @noise-kngdm @amerigal

2022-01-08 17:21 UTC, danifm1321 requested changes
Te propongo un par de cositas para que cambies en el código de momento.

2022-01-08 17:21 UTC, danifm1321 commented on tests/test_tablero.py
> +Pieza.TORRE_BLANCO,Pieza.CABALLO_BLANCO,Pieza.ALFIL_BLANCO,Pieza.REINA_BLANCO,Pieza.REY_BLANCO,Pieza.ALFIL_BLANCO,Pieza.CABALLO_BLANCO,Pieza.TORRE_BLANCO]
Creo que puedes hacer esta inicialización de una manera más sencilla, con bucles o algo por el estilo.

2022-01-08 17:21 UTC, danifm1321 commented on tracker/tablero.py
> +    def get_posicion(self):
Échale un ojo a las buenas prácticas para construir getters en python, tiene su forma propia

2022-01-08 18:33 UTC, noise-kngdm requested changes
Te he puesto unos cuantos comentarios, creo falta algo de trabajo todavía.

2022-01-08 18:33 UTC, noise-kngdm commented on docs/criteriosObjetivo3.md
> +Se ha elegido Poetry frente a pip tras algo de investigación debido a que su eficiencia respecto a este último es mayor, dando una mejor performance. Además, es mucho más sencillo en su instalación y
Esto está completamente mal.
pip es un gestor de paquetes, como apt o pacman pero para paquetes de Python. Poetry es un gestor de **dependencias**. Además Poetry no puede tener un rendimiento mejor que pip puesto que **usa pip**. Tampoco es más sencillo en su instalación puesto que pip está en casi todos los repos oficiales de los diferentes SOs, mientras que Poetry tienes que instalarlo usando un script que está mantenido por el propio proyecto.

Revisa toda esta sección.

2022-01-08 18:33 UTC, noise-kngdm commented on docs/criteriosObjetivo3.md
> +Se trata de un task runner especificamente utilizado para python, que en muchos sentidos tiene una forma de uso similar a Make con el cual la mayoría de desarrolladores estan familiarizados. Además,
Este apartado está muy flojo. ya que no has puesto los criterios que vas a usar para elegir el task runner **a priori**, ni has considerado diferentes alternativas.

2022-01-08 18:33 UTC, noise-kngdm commented on docs/criteriosObjetivo4.md
> +Los tests deben de intentar enfocarse en probar todas las posibles entradas invalidas o posibles argumentos ilegales, así, como en caso de tener apliaciones mas complejas que la desarrollada en este
Has puesto qué son los principios F.I.R.S.T., lo cual está bien, pero no has puesto por qué tus tests los cumplen, que es lo que pedía el check que has marcado en la descripción del PR.

2022-01-08 18:33 UTC, noise-kngdm commented on docs/criteriosObjetivo4.md
> +Se ha seleccionado Pytest sobre su principal competidor en python Unittest. Ambas son buenas opciones, ampliamente utilizadas en la comunidad de python, pero he optado por el uso del primero, pytest,
Podrías haber considerado más alternativas como nose.

2022-01-08 18:33 UTC, noise-kngdm commented on docs/criteriosObjetivo4.md
> +En este caso, assertpy, tiene una sintaxis muy cómoda y me gustaría resaltar este aspecto respecto a otras bibliotecas, ya que parece utilizar casi el lenguaje natural. También tenemos una gran canti
Podrías poner un ejemplo de qué aserciones tiene `assertpy` que `Grappa` no que crees que podrían ser útiles en un futuro.

2022-01-08 18:33 UTC, noise-kngdm commented on tracker/partidachess.py
> +   def get_nombre_blancas(self):
Los getter no se suelen hacer así en Python. Échale un ojo a [cómo se usa el decorador @property](https://realpython.com/python-property/).

2022-01-08 18:33 UTC, noise-kngdm commented on tracker/partidachess.py
> +    	Atributos
Esto no serían atributos sino parámetros. De todas formas yo lo escribiría en inglés, que es como está en la [guía de estilo de numpy](https://numpydoc.readthedocs.io/en/latest/format.html), el formato que parece que utilizas.
```suggestion
    	Parámetros
```

2022-01-08 18:33 UTC, noise-kngdm commented on tracker/tablero.py
> +            self._posicion = []
Aquí deberías levantar una excepción de tipo `ValueError`, si no estás dejando el programa en un estado inconsistente.

2022-01-08 21:45 UTC, xCyal commented
> Te he puesto unos cuantos comentarios, creo falta algo de trabajo todavía.

Lo primero, muchas gracias por el feedback, voy a revisar todos los puntos que me has comentado, a excepción quizás de lo relacionado con poetry e invoke ya que esa documentación es del objetivo anterior, el cual aun no ha sido aceptado por lo que voy a tratarlo por separado y cuando lo tenga listo hare merge de las branch.

Por lo demás estoy de acuerdo con los cambios propuestos y de nuevo muchas gracias por el tiempo dedicado, mañana sin falta actualizaré esta rama.

2022-01-09 17:35 UTC, xCyal commented on tracker/tablero.py
> +    def get_posicion(self):
Cierto, voy a revisar esta parte.

2022-01-09 17:36 UTC, xCyal commented on tests/test_tablero.py
> +Pieza.TORRE_BLANCO,Pieza.CABALLO_BLANCO,Pieza.ALFIL_BLANCO,Pieza.REINA_BLANCO,Pieza.REY_BLANCO,Pieza.ALFIL_BLANCO,Pieza.CABALLO_BLANCO,Pieza.TORRE_BLANCO]
Voy a intentar idear algún bucle para inicializarlo, al menos para que quede más claro.

2022-01-09 17:36 UTC, xCyal commented
> Te propongo un par de cositas para que cambies en el código de momento.

Gracias por el tiempo, de nuevo.

2022-01-19 17:10 UTC, JJ requested changes
Prácticamente ningún commit sigue las buenas prácticas: son "actualiza esto, pone lo otro". Los commits deben indicar por qué se ha hecho algo y cómo soluciona un problema. Ninguno de ellos parece tampoco apuntar a un issue, ni por supuesto a historias de usuario. La mitad de los commits no están "verified", lo que no tiene mucha importancia, pero ya que se hace, que se haga bien. Se insiste en el error de usar pylint para comprobar la sintaxis, copiando a otros muchos compañeros a los que ya se le había indicado que estaba mal. 
Los tests ni siquiera hacen referencia a ningún issue ni a nada, el commit es "añadir test". No supera este objetivo.

2022-01-19 18:23 UTC, xCyal commented
> Prácticamente ningún commit sigue las buenas prácticas: son "actualiza esto, pone lo otro". Los commits deben indicar por qué se ha hecho algo y cómo soluciona un problema. Ninguno de ellos parece tampoco apuntar a un issue, ni por supuesto a historias de usuario. La mitad de los commits no están "verified", lo que no tiene mucha importancia, pero ya que se hace, que se haga bien. Se insiste en el error de usar pylint para comprobar la sintaxis, copiando a otros muchos compañeros a los que ya se le había indicado que estaba mal. Los tests ni siquiera hacen referencia a ningún issue ni a nada, el commit es "añadir test". No supera este objetivo.

@JJ disculpe por no haber mencionado que este objetivo se iba a rehacer en base al nuevo trabajo de la convocatoria extraordinaria, podía haberle ahorrado este trabajo. De todas formas menos mal que ha realizado el comentario ya que estaba trabajando en ocasiones desde el ordenador de casa y por algún despiste no lo tenía bien configurado, y en el portátil sí, por eso lo de algunos commits no verificados, ya está arreglado.

Respecto a los revisores @danifm1321 @noise-kngdm  muchas gracias por haber echado una mano y deciros que no significa que no vaya a tener en cuenta vuestros comentarios ya que serán la base para el nuevo PR, solo que quería empezar de nuevo el proyecto dado que debido a las prisas de intentar entregarlo en la ordinaria no estaba teniendo mucha rigurosidad.

2022-01-19 19:33 UTC, JJ commented
Espero que la corrección te ayude, de todas formas. Tenías derecho a ella
en todo caso.

2022-02-13 12:30 UTC, closed without merging