Creación de generalJourney.md en docs
xCyal/A-Tracker pull request #2
Opened 2021-12-02 11:35 UTC by xCyal

Archivo que contiene tanto la descripción de los usuarios como enlaces a sus historias y los milestones de la aplicación.

2021-12-02 12:13 UTC, xCyal commented
He hecho link entre los Milestones y los issues de historias de usuario trás fallar el check en el PR.

Listo para revisión.

2021-12-07 12:21 UTC, JJ commented
> He hecho link entre los Milestones y los issues de historias de usuario trás fallar el check en el PR.
> 
> Listo para revisión.

No se trata de que "hagas link". Se trata de que entiendas que los milestones son la forma de organizar el desarrollo en diferentes etapas, y que lo que el cliente pide se va a organizar también en la misma cantidad de productos de complejidad creciente.

2021-12-07 12:23 UTC, JJ requested changes
Por favor, mira la guía de comprobación y también los errores frecuentes que se han puesto en las diferentes sesiones de clase.

2021-12-07 12:23 UTC, JJ commented on docs/generalJourney.md
> +- [M0](https://github.com/xCyal/A-Tracker/milestone/1) Creación clase Usuario.
Los milestones son productos mínimamente viables, no tareas. Por favor, mira la lista de comprobación de este objetivo, pégala en el cuerpo de este PR y síguela.

2021-12-10 12:06 UTC, xCyal commented on docs/generalJourney.md
> +- [M0](https://github.com/xCyal/A-Tracker/milestone/1) Creación clase Usuario.
> Los milestones son productos mínimamente viables, no tareas. Por favor, mira la lista de comprobación de este objetivo, pégala en el cuerpo de este PR y síguela.

Listo para revisión, he estado revisando varios objetivos 1 de varios compañeros, lo único que no estoy seguro es del punto 11, de sí tendría que describir de manera mas concisa cuales son los objetivos dentro de cada milestone que se deben alcanzar.

2021-12-10 12:50 UTC, JJ reviewed
Mira la [lista de comprobación de este objetivo en el apartado de Milestone](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura#listas-de-comprobaci%C3%B3n). Tienes que tratar de entender qué es un milestone, un PMV, para poder superar este objetivo.
Las HUs parecen razonables, aunque tienes que tener en cuenta que toda la lógica de negocio que tenga tendrás que programarla tú.

2021-12-10 12:50 UTC, JJ commented on README.md
> +Puedes encontrar más información sobre el proyecto en /docs.
Por favor, pon enlaces cuando te refieras a otra parte del repo.

2021-12-11 22:15 UTC, xCyal commented
Cambios realizados a los milestones:
- Se tratan de PMV en su definición: El Producto Mínimo Viable es, por lo tanto, un prototipo de tu producto que tiene las funcionalidades mínimas para poder presentarlo a tus clientes y verificar si les interesa. Cada uno de estos sistemas tiene la funcionalidad mínima en su área dentro de la aplicación, sirviendo para verificar si cada uno de ellos se adapta de manera correcta

- Cambio en el orden de los milestones para dar más sentido a los mismos, el 0 es el esencial, el resto se construyen sobre el.

- No existen PMVs entre los milestones ( Por ejemplo M0 y M2 ) 

- Se indica cual es el objetivo de cada uno de estos milestones siendo posible comprobar que se ha alcanzado el objetivo.

2021-12-12 11:00 UTC, JJ commented
> Archivo que contiene tanto la descripción de los usuarios como enlaces a sus historias y los milestones de la aplicación.
> 
> Lista de comprobación:
> 
> 1.¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
> 
> 2.¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
> 
> 3.¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
> 
> 4.¿El milestone 0 tiene asignada alguna historia de usuario?
> 
> 5.¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?

¿Qué es lo que describe tu milestone cero?
> 
> 6.¿Todos los milestones describen correctamente un producto, y no un concepto vago, una funcionalidad o una tarea?
> 

La lista de comprobación es para que la marquéis, no para que la copiéis. ¿En serio crees que tus milestones no describen una funcionalidad? ¿Sistema de almacenamiento no es una funcionalidad?

> 7.¿Los milestones son graduales, o hay un salto grande entre ellos?
> 
> 8.¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
> 
> 9.¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
> 
> 10.¿El milestone 0 es mínimo y viable?
> 
> 11.¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
> 
> 12.¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?
> 
> Sobre las historias de usuario
> 
> 1.¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube en las mismas?
> 
> 2.¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?
> 
> 3.¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un user journey para aclararlo?
> 
> 4¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios desean hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2021-12-12 11:01 UTC, JJ commented
Haz la lista de comprobación *de verdad* y ponlo explícitamente para revisión, por favor.

2021-12-12 14:37 UTC, xCyal commented
Lista de comprobación:

1.¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
 * [x] 
2.¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
 * [x]
3.¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
 * [x] El primero es esencial para que los siguientes tengan sentido.
4.¿El milestone 0 tiene asignada alguna historia de usuario?
 * [x] 
5.¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?
 * [x] 
6.¿Todos los milestones describen correctamente un producto, y no un concepto vago, una funcionalidad o una tarea?
 * [x] Se trata de PMVs, en este caso diferentes módulos (productos informáticos), a diferencia de lo descrito previamente, que eran funcionalidades.
7.¿Los milestones son graduales, o hay un salto grande entre ellos?
 * [x] Tienen un orden lógico y gradual.
8.¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
 * [x] M0 Es interno, 
9.¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
 * [x] 
10.¿El milestone 0 es mínimo y viable?
 * [x] Sí, este módulo esta bien definido como tal. 
11.¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
 * [x]
12.¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?
 * [x]

2021-12-12 14:47 UTC, xCyal commented
> Haz la lista de comprobación _de verdad_ y ponlo explícitamente para revisión, por favor.

Listo para revisión, he revisado de nuevo los conceptos en el video de "PMV" y buscado más información sobre estos, ahora claramente no se esta describiendo las funcionalidades (como se hacía previamente) y los milestones se describen como un producto informático (en este caso módulos, pudiendo obviamente añadirse más PMVs posteriormente para describir la aplicación de forma completa).

2021-12-12 19:09 UTC, JJ approved these changes
Creo que @francisco3207 todavía no había hecho el segundo objetivo, así que él tendrá que trabajar sobre él.
Para ti, lo único que se me ocurre es que intentes echar una mano a @manujurado1 a ver si puede avanzar al 1 y luego le ayudas tú a superar el 2.

2021-12-16 13:19 UTC, xCyal commented
> Creo que @francisco3207 todavía no había hecho el segundo objetivo, así que él tendrá que trabajar sobre él. Para ti, lo único que se me ocurre es que intentes echar una mano a @manujurado1 a ver si puede avanzar al 1 y luego le ayudas tú a superar el 2.

Perfecto, sigo a la espera, voy a intentar ponerme en contacto con el por si necesita alguna ayuda.

2021-12-16 13:32 UTC, merged