Objetivo 3 ex
xCyal/A-Tracker pull request #20
Opened 2022-01-19 17:19 UTC by xCyal

Lista de comprobación del objetivo 3:

1. * [x]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores? Sí, tal y como se indica en el guión del objetivo.

2. * [x]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue? Sí, se generaron 2 issues previos a la creación del código, es decir, el código viene dado por estos issues.

3. * [x]  ¿Ese issue está asignado a un milestone? Sí.

4. * [x]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas? Se utiliza invoke únicamente como task runner.

5. * [x]  ¿El PR, que también es un issue, está asignado al mismo milestone? Sí.

Diferencias claras respecto al PR de la convocatoria ordinaria:

- Se ha optado por no utilizar un gestor de dependencias más allá de utilizar pip (dado que viene por defecto con python) e indicar como instalar invoke desde pip, dado que no era necesario para este objetivo realizar comparaciones entre gestores ni "elegir" uno. Previamente se utilizaba poetry.

- No se utiliza pylint, no es necesario. Se comprueba que compile el código compilandolo con py_compile.

- Se ha documentado correctamente como utilizar el gestor de tareas desde el README.md y Objetivo-3.md

- Se ha creado el código desde el issue correspondiente.

2022-01-19 17:23 UTC, JJ commented
⛹ Revisores → @lentes4k @Parka015 @Asmilex

2022-01-19 18:24 UTC, lentes4k requested changes
Buen trabajo! La verdad es que se nota que le has echado un ratito. Pero tengo varias cosas que comentarte.

1. Has elegido invoke, pero ¿por qué no Poetry (siendo esta además la opción recomendada por la comunidad) u otra opción existente? -> te dejo una pista abajo 🙈 
2. Una vez has elegido invoke como gestor, ¿por qué no metes la instalación de dependencias también? de esta manera añades facilidad y mejoras la automatización. Además, ¡para los siguientes objetivos te va a venir genial!


Pista: a pesar de que Poetry es la recomendada puedes decir que aún a día de hoy es ampliamente usada...jeje

Por lo demás no veo nada más así que me llame la atención.
¡Ánimo que en estas fechas es necesario! 😄

2022-01-20 10:49 UTC, xCyal commented
Se ha añadido Poetry al proyecto, mencionando su uso en la documentación y cambiando la forma de instalar las dependencias que se cita en el README.md. Como se ha mencionado antes, no se indican las razones de su elección como gestor de dependencias en la documentación, solo una breve descripción del mismo.

2022-01-20 12:39 UTC, xCyal commented
> Realmente llevas razón, como gestor de tareas no es muy usando Poetry. Para dependencias sí y más recomendable que `pip`. Aún así, en mi entrega lo usé como gestor de tareas al permitir la programación de unos scripts dentro del `pyproject.toml`. A modo de ejemplo te muestro cómo lo hice yo:
> 
> ```
> [tool.poetry.scripts]
> test = 'test.tests:Tests'
> check = 'test.script_check:check'
> ```
> 
> Con la declaración de `[tool.poetry.scripts]` le indico que voy a nombrar una serie de scripts. Basicamente consigo que cuando invoque `poetry run test` se vaya al fichero `test.py` dentro del directorio `tests` y lance la función `Tests`. Yo lo hice de este modo porque me ahorraba una dependencia, aunque si puede resultar algo más engorroso que `invoke`. Me equivoqué al decirte que es la recomendada por la comunidad (ya que no lo es, Poetry es la recomendada para dependencias, para tareas sigue siendo `invoke` aunque con Poetry también se pueda). Por lo demás creo que se cumplen los criterios. Por mi parte tienes el aprobado. Seguiré por aquí si necesitas algo y ¡a por los siguientes! 😄

Eso mismo estaba pensando, es decir sabía que era posible ejecutar scripts con Poetry dentro del entorno, pero me estaba volviendo un poco loco con lo de que Poetry era el gestor de tareas recomendado buscando información al respecto 😆 . De todas formas aun siendo una opción viable la forma de trabajar con invoke me parece bastante cómoda, por lo que lo mantendré como gestor de tareas.

Por lo demás me alegra que hayas comentado lo del gestor de dependencias, realmente creo que es y será super útil en el resto de objetivos 👍 

De nuevo muchas gracias por el tiempo y ganas @lentes4k! 🤝 

En principio si ningún revisor tiene nada que decir al respecto, este PR creo que esta listo para revisión! 💪 

PD: Me he apropiado del uso de emojis, realmente le dan otra vidilla a esto 🤣

2022-01-21 11:07 UTC, Asmilex commented
> Eso mismo estaba pensando, es decir sabía que era posible ejecutar scripts con Poetry dentro del entorno, pero me estaba volviendo un poco loco con lo de que Poetry era el gestor de tareas recomendado buscando información al respecto 😆 . De todas formas aun siendo una opción viable la forma de trabajar con invoke me parece bastante cómoda, por lo que lo mantendré como gestor de tareas.
> 
> Por lo demás me alegra que hayas comentado lo del gestor de dependencias, realmente creo que es y será super útil en el resto de objetivos 👍
> 

En principio, el objetivo está bastante bien. Se ve que los cimientos están asentados.

Sin embargo, creo que sería importante justificar un poquito mejor los motivos por los que se han elegido estas herramientas en el archivo `Objetivo3.md`. Por ejemplo, 

> La elección de invoke como task runner se ha tomado en base a lo mencionado previamente, especialmente por su parecido con make a la vez que nos permite definir las funciones al estilo de python.

Parece un poco pobre a priori. Te recomiendo que le eches un ojo a los PRs de los compañeros para ver cómo se evalúa el objetivo 3. Viene bien para saber por dónde te van a atacar ⚔️.

También sería conveniente que le echaras un ojo a la descripción original del PR. Tiene información desactualizada.

2022-01-21 12:14 UTC, xCyal commented
> > Eso mismo estaba pensando, es decir sabía que era posible ejecutar scripts con Poetry dentro del entorno, pero me estaba volviendo un poco loco con lo de que Poetry era el gestor de tareas recomendado buscando información al respecto 😆 . De todas formas aun siendo una opción viable la forma de trabajar con invoke me parece bastante cómoda, por lo que lo mantendré como gestor de tareas.
> > Por lo demás me alegra que hayas comentado lo del gestor de dependencias, realmente creo que es y será super útil en el resto de objetivos 👍
> 
> En principio, el objetivo está bastante bien. Se ve que los cimientos están asentados.
> 
> Sin embargo, creo que sería importante justificar un poquito mejor los motivos por los que se han elegido estas herramientas en el archivo `Objetivo3.md`. Por ejemplo,
> 
> > La elección de invoke como task runner se ha tomado en base a lo mencionado previamente, especialmente por su parecido con make a la vez que nos permite definir las funciones al estilo de python.
> 
> Parece un poco pobre a priori. Te recomiendo que le eches un ojo a los PRs de los compañeros para ver cómo se evalúa el objetivo 3. Viene bien para saber por dónde te van a atacar ⚔️.
> 
> También sería conveniente que le echaras un ojo a la descripción original del PR. Tiene información desactualizada.

Muy buenas @Asmilex ✋ , perfecto, tienes razón. Ya he actualizado el PR para mencionar el uso de Poetry (especificando que este PR respecto al anterior cambia en el hecho de no mencionar los motivos de elección del mismo). 

Es cierto lo que dices de la documentación, es un poco pobre, voy a dedicarle un poco más de trabajo, es lo que más me esta costando de estos objetivos, creo que voy a hacerte caso y a revisar la documentación de algunos compañeros a modo de inspiración 👍 

Muchas gracias!

2022-01-21 13:49 UTC, xCyal commented
> > Eso mismo estaba pensando, es decir sabía que era posible ejecutar scripts con Poetry dentro del entorno, pero me estaba volviendo un poco loco con lo de que Poetry era el gestor de tareas recomendado buscando información al respecto 😆 . De todas formas aun siendo una opción viable la forma de trabajar con invoke me parece bastante cómoda, por lo que lo mantendré como gestor de tareas.
> > Por lo demás me alegra que hayas comentado lo del gestor de dependencias, realmente creo que es y será super útil en el resto de objetivos 👍
> 
> En principio, el objetivo está bastante bien. Se ve que los cimientos están asentados.
> 
> Sin embargo, creo que sería importante justificar un poquito mejor los motivos por los que se han elegido estas herramientas en el archivo `Objetivo3.md`. Por ejemplo,
> 
> > La elección de invoke como task runner se ha tomado en base a lo mencionado previamente, especialmente por su parecido con make a la vez que nos permite definir las funciones al estilo de python.
> 
> Parece un poco pobre a priori. Te recomiendo que le eches un ojo a los PRs de los compañeros para ver cómo se evalúa el objetivo 3. Viene bien para saber por dónde te van a atacar ⚔️.
> 
> También sería conveniente que le echaras un ojo a la descripción original del PR. Tiene información desactualizada.

De acuerdo, en principio, la documentación esta bastante más completa, además de limpia. De todas formas agradecería una opinión externa ya que he dejado constancia en anteriores PRs de que escribir documentación no es mi fuerte (por ahora 😆)

2022-01-23 12:35 UTC, xCyal commented
En principio este PR esta listo para revisión.

Voy a continuar durante el día de hoy con el siguiente objetivo tomando este de base. Muchas gracias de nuevo a los revisores! 💪

2022-01-23 12:40 UTC, Asmilex commented on docs/Objetivo-3.md
> +En general, es una opción de uso sencillo y que se adapta a las necesidades de este proyecto.
Creo que los motivos siguen sin ser muy sólidos. 

- Escribir en estilo Python no parece una ventaja a priori. Casi todos lo hacen. 
- El tercer punto parece un poco opinión personal. Es importante matizarlo. Aquí, en principio, buscamos motivos objetivos. 

Creo que todavía sería necesario hacer una lista de requisitos objetivos que debe tener un task runner, y hacer comparaciones entre diferentes herramientas.

2022-01-23 12:54 UTC, xCyal commented on docs/Objetivo-3.md
> +En general, es una opción de uso sencillo y que se adapta a las necesidades de este proyecto.
De acuerdo, voy a revisar lo que me comentas:

Voy a mencionar que estos motivos que a priori no son objetivos son personales, que en principio siguen siendo motivos para la elección. 

Además voy a añadir una pequeña comparativa con otros posibles task runners (como se hace en parte al mencionar a Poetry en este apartado).

2022-01-23 14:24 UTC, xCyal commented
Se ha añadido a la documentación del task runner una comparativa con otros Task runners y se ha mencionado en el tercer punto que es una visión personal que ha motivado en parte la elección, sin pretender que sea un motivo para otras personas, pero en mi caso lo fue y creo que debe ser mencionado ya que es un criterio más de elección en este proyecto.

2022-02-03 14:50 UTC, xCyal commented
Estoy revisando todos los objetivos, teniendo en cuenta errores frecuentes así como errores de mis compañeros.

Marcaré con un ✅ los que creo que ya he abordado y se hará un commit si encuentro algún error sobre ellos.

Errores frecuentes recopilados sobre el Objetivo 3 mencionados por @JJ:

- La infraestructura también forma parte de la planificación, y se merece un issue. ✅ 📎 Existe un issue asociado.
- Siempre se trabaja hacia un producto mínimamente viable, así que ese issue debe estar en el milestone correspondiente. ✅ 
- pylint no comprueba sintaxis, sino que es un linter. ✅ 📎 No se utiliza pylint
- No distinguir entre dependencias "de producción" y dependencias "de desarrollo". Las dependencias de producción son las que se van a desplegar, los gestores de tareas serían dependencias del desarrollo. ✅ 📎 Nunca se menciona el gestor de tareas como una "herramienta de producción"

Iré actualizando el comentario si voy encontrando más, voy a darme un paseo por los PRs de compañeros para ver las correcciones y ver si se pueden aplicar aquí.

2022-02-08 12:22 UTC, JJ commented
Te digo igual que antes, recuerda cerrar el PR anterior desde este y referenciar lo que se te haya dicho allí.

2022-02-08 12:23 UTC, JJ approved these changes
:+1:

2022-02-08 12:57 UTC, merged