Creación partidaChess.py
xCyal/A-Tracker pull request #9
Opened 2021-12-22 14:34 UTC by xCyal

Fichero de la clase partidaChess.py para el objetivo 2

2021-12-22 15:14 UTC, JJ commented
⛹ Revisores → @paula1999 @Pablont98 @vlljuan99

2021-12-23 12:42 UTC, JJ requested changes
No sigues la metodología normal de desarrollo de hacerlo desde un HU, pasando por un issue. Ningún commit se asocia a ningún issue.

2021-12-23 20:08 UTC, xCyal commented
Dado que el objetivo estoy realizandolo sobre mi propio trabajo, voy a copiar la lista de comprobación del objetivo 2 para poder estar seguro de cumplir los requisitos necesarios para superarlo. En caso de que alguno de los revisores se pase por aquí agradezco las aportaciones y críticas.


Sobre la estructura del repositorio

1. ¿He seguido las mejores prácticas en nombre de las clases y ficheros y disposición de los mismos? * [] 

Sobre el análisis del problema
1. ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado? * [] 
2. ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado? * [] 
3. ¿He propuesto un producto mínimamente viable, que en general será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?. * [] 

Sobre la planificación y la programación

1. ¿Los issues representan un problema, y no una tarea? * [] 
2. ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado? * [] 
3. ¿Los mensajes de commit siguen el el formato estándar y las buenas prácticas. * [] 
4. ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU? * [] 
5. ¿Todos los issues creados están asignados a una HU? * [] 
6. ¿Todos los cambios en el código están asignados a un issue? * [] 
7. Los issues sobre los que estoy trabajando, ¿han sido asignados al primer milestone? * [] 
8. ¿Se ha asignado al mismo milestone el PR que se ha hecho? * [] 
10. ¿Son los milestones sobre los que estoy trabajando productos mínimamente viables? ¿O tengo que solicitar al product manager que cree milestones adicionales o precise de qué producto se trata? * []

2021-12-25 14:51 UTC, xCyal commented
Rediseñados los issues para realizar el desarrollo partiendo de las HU. Renombradas las variables y clases para ceñirme al estándar en python.

2021-12-25 15:06 UTC, xCyal commented
Listo para revisión, en este caso creo que por los revisores asignados.

2021-12-28 21:50 UTC, xCyal commented
> ⛹ Revisores → @paula1999 @Pablont98 @vlljuan99

Me preguntaba si alguno me podría dar algo de feedback, voy a comenzar con el objetivo siguiente para ir adelantando trabajo.

2022-01-08 19:05 UTC, JJ requested changes
No se ha seguido la metodología correcta, por lo que el código generado no es válido.

2022-01-08 19:05 UTC, JJ commented on Tracker/partidachess.py
> +    def __init__(self, nombres, jugador_inicial,ganador,movimientos):
Si este commit no está asociado a ningún issue ni HU, es simplemente inválido. Ya se te comentó que había que seguir esa metodología. Rehacer los HUs no es suficiente, habría sino necesario cerrar este PR y escribir el código que *realmente* requiere las HUs y la lógica de negocio.

2022-01-08 20:01 UTC, xCyal commented on Tracker/partidachess.py
> +    def __init__(self, nombres, jugador_inicial,ganador,movimientos):
Entiendo el hecho de que el error esta en no haber asociado el commit al issue, pero en este caso, considero que el código esta pensado desde una historia de usuario por lo que no deja de ser valido, me pregunto si es necesario realmente reabrir el PR o crear un nuevo commit esta vez si asociado a #3 o #4. Gracias por todo.

2022-02-07 19:15 UTC, JJ commented
Si lo vas a desarrollar en otro lado, lo correcto habría sido cerrar este. Alternativamente puedes indicar que lo cierras cuando resuelvas los problemas que se han planteado.

2022-02-07 19:23 UTC, xCyal commented
> Si lo vas a desarrollar en otro lado, lo correcto habría sido cerrar este. Alternativamente puedes indicar que lo cierras cuando resuelvas los problemas que se han planteado.

Sí, no lo cerré por la importancia de tener en cuenta lo que se mencionan en las correcciones de este PR para el nuevo.
Voy a mencionar en el propio PR que se cerrará cuando se resuelva dicho objetivo. 👍

2022-02-08 12:50 UTC, closed without merging